import SwiftUI

// MARK: - Risk Assessment View

struct RiskAssessmentView: View {
    let claim: Claim
    
    var body: some View {
        ScrollView {
            VStack(spacing: 24) {
                // Risk Score Card
                GroupBox {
                    VStack(spacing: 16) {
                        // Risk Score Circle
                        ZStack {
                            Circle()
                                .stroke(DeevoColors.border, lineWidth: 8)
                                .frame(width: 120, height: 120)
                            
                            Circle()
                                .trim(from: 0, to: riskScore / 100)
                                .stroke(riskColor, style: StrokeStyle(lineWidth: 8, lineCap: .round))
                                .frame(width: 120, height: 120)
                                .rotationEffect(.degrees(-90))
                            
                            VStack(spacing: 4) {
                                Text("\(Int(riskScore))")
                                    .font(.system(size: 36, weight: .bold))
                                    .foregroundColor(riskColor)
                                Text("Risk Score")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                        }
                        
                        // Risk Level Badge
                        Text(riskLevel)
                            .font(.headline)
                            .padding(.horizontal, 16)
                            .padding(.vertical, 8)
                            .background(riskColor.opacity(0.2))
                            .foregroundColor(riskColor)
                            .cornerRadius(8)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 8)
                } label: {
                    Label("Overall Risk Assessment", systemImage: "exclamationmark.shield")
                }
                
                // Risk Factors
                GroupBox {
                    VStack(alignment: .leading, spacing: 12) {
                        RiskFactorRow(title: "Claim History", value: "Low", color: DeevoColors.riskLow)
                        RiskFactorRow(title: "Damage Severity", value: "Moderate", color: DeevoColors.riskModerate)
                        RiskFactorRow(title: "Documentation Quality", value: "Good", color: DeevoColors.riskLow)
                        RiskFactorRow(title: "Fraud Indicators", value: "None Detected", color: DeevoColors.success)
                    }
                } label: {
                    Label("Risk Factors", systemImage: "list.bullet.clipboard")
                }
                
                // AI Disclaimer
                HStack(alignment: .top, spacing: 12) {
                    Image(systemName: "info.circle.fill")
                        .foregroundColor(DeevoColors.accent)
                    
                    Text("This risk assessment is generated by AI and is for advisory purposes only. Final decisions should be made by qualified adjusters.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
                .padding()
                .background(DeevoColors.accent.opacity(0.1))
                .cornerRadius(8)
            }
            .padding()
        }
    }
    
    private var riskScore: Double {
        // Calculate risk score based on claim data
        // This is a placeholder - real implementation would use AI/ML
        switch claim.priority {
        case .urgent: return 85
        case .high: return 65
        case .medium: return 45
        case .low: return 25
        }
    }
    
    private var riskLevel: String {
        switch riskScore {
        case 0..<30: return "Low Risk"
        case 30..<50: return "Moderate Risk"
        case 50..<70: return "Elevated Risk"
        default: return "High Risk"
        }
    }
    
    private var riskColor: Color {
        switch riskScore {
        case 0..<30: return DeevoColors.riskLow
        case 30..<50: return DeevoColors.riskModerate
        case 50..<70: return DeevoColors.riskElevated
        default: return DeevoColors.riskCritical
        }
    }
}

// MARK: - Risk Factor Row

struct RiskFactorRow: View {
    let title: String
    let value: String
    let color: Color
    
    var body: some View {
        HStack {
            Text(title)
                .font(.subheadline)
            Spacer()
            Text(value)
                .font(.subheadline)
                .fontWeight(.medium)
                .foregroundColor(color)
        }
    }
}

#Preview {
    RiskAssessmentView(claim: Claim(
        claimNumber: "CLM-2026-001",
        customerName: "John Doe",
        vehicleMake: "Toyota",
        vehicleModel: "Camry",
        vehicleYear: 2022
    ))
}
